server:
  port: 443

  ssl:
    key-store: file:keystore.jks
    key-password: 123456
    key-store-password: 123456
    key-alias: proxy
    trust-store: file:truststore.jks
    trust-store-password: 123456

spring:
  application:
    name: zuul

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    registryFetchIntervalSeconds : 5
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info,routes

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  host:
    socket-timeout-millis: 5000000
    connect-timeout-millis: 5000000

ribbon:
  ServerListRefreshInterval: 1000
  ReadTimeout: 10000
logging:
  file:
    path: .
